--[[
	© 2018 devultj.co.uk, do not share, re-distribute or modify

	without permission of its author (devultj@gmail.com) - {{ user_id }}
]]

i18n.registerPhrases( "de", {
    bag_regular = "Reguläre Tasche",
    bag_luxury = "Luxsus Tasche",
    bag_enhanced = "Verbesserte Tasche",
    loot_cash_roll_small = "Kleine Rolle Bargeld",
    loot_golden_figure = "SecuroServ Goldene Figure",
    loot_silver_figure = "SecuroServ Silberne Figure",
    loot_cash_case = "Koffer voll Geld",
    loot_cash_pallet = "Palette voll Geld",
    cooldown_3d = "Abklingzeit",
    loot_worth = "wert %s",
    stealing_bag = "TASCHE AUFHEBEN",
    picking_up_loot = "BEUTE AUFHEBEN",
    picking_up_bag = "TASCHE AUFHEBEN",
    confiscating_bag = "TASCHE BESCHLAGNAHMEN",
    confiscate_bag_text = "Du hast %s verdient, durch das beschlagnahmen einer Tasche",
    bag_sold_text = "Du hast %s verdient, durch das verkaufen von %s",
    no_items = "KEINE GEGENSTÄNDE",
    carrying_text = "SIE TRAGEN:",
    throw_item = "UM ZU WERFEN",
    un_equip_mask = "MASKE ABNEHMEN",
    equip_mask = "MASKE AUFZIEHEN",
    drop_action_text = "[SHIFT+%s] ZUM ABWERFEN",
    picking_up_mask = "MASKE AUFHEBEN",
    dropping_mask = "MASKE ABLEGEN",
    equipping_mask = "MASKE AUFZIEHEN",
    un_equipping_mask = "MASKE ABNEHMEN",
    zone_being_robbed = "%s is being robbed!",
    click_to_disable_alarm = "Disable Alarm",
    cctv_title = "CCTV",
    screen_restock = "CLOSED",
    screen_active = "OPEN",
    loot_hint_text = "You need a Bag",
    already_have_bag = "You already have a Bag",
    already_in_zone_creator = "You are already in the Zone Creator.",
    no_access = "You do not have access to this.",
    no_access_x = "You do not have access to %s.",
    zone_created = "You created a zone.",
    zone_duplicate = "A zone with this name already exists.",
    save_zone_prompt = "Press Y and press 'Save' to save your changes",
    save_zone = "Save",
    editing_zone = "Editing Zone '%s'",
    zone_saved_x = "You saved data for '%s'",
    drill_active = "Drill is active.",
    cooldown_active = "Cooldown is active.",
    required_tools = "Required tools:%s",
    not_enough_cops = "Not enough Police online.",
    reloaded_zones = "You reloaded all Zones.",
    delete_zone_confirmation = "Are you sure you want to delete this zone?",
    deleted_zone = "You deleted a Zone.",
    yes = "Yes",
    no = "No"
} )
